### PR TITLE
Create Pythonista-FAQ.md

### PR DESCRIPTION
**Pull request by cclauss**
See: https://forum.omz-software.com/topic/3550/we-need-a-faq

### CODE REVIEW

**Comment by Evan03Davis** [comment]
Love the idea! I think you should start a thread and ask the community what FAQ should be posted and then make one and pin it. This would be incredibly useful for newbies,

**Comment by cclauss** [comment]
@zrzka Your thoughts on hosting a FAQ here or elsewhere?

**Comment by zrzka** [comment]
@cclauss hard to answer it ... Several thoughts ... I think Pythonista needs some FAQ for sure. Question is where to include it, where to host it ...

Ideal situation would be a repository where community can work on it and it will be included in the Pythonista itself. Just another link in the documentation browser. We can't decide this, just @omz can do it. Even more ideal situation would be repository with [documentation](http://omz-software.com/pythonista/docs/) where people can send PRs to fix simple documentation issues (like wrong default value, etc.) or even more complex ones.

Another option would be to introduce some kind of community GitHub organization, with several repos (examples, faq, ...), ... where one of the repository can be FAQ site written in reST, generated with Sphinx and hosted at readthedocs.io. I personally don't like Wiki or MD documents in the repo. Some well known URL with generated content is much better IMHO. Sphinx is pretty powerful. But I still feel that it should be kind of coordinated with @omz.

It doesn't make much sense to have official documentation, community documentation elsewhere, ... It's slightly better if the community documentation can be linked from the official one. Also there's a forum, maybe FAQ can be incorporated there somehow? Don't know.

As I wrote, hard to answer ...

**Comment by dgelessus** [comment]
We could make a repo for documentation under [Pythonista-Tools](https://github.com/Pythonista-Tools).

**Comment by cclauss** [comment]
Moved to https://github.com/Pythonista-Tools/Pythonista-Documentation

**Pull request closed without merging**
